import sounddevice as sd
import numpy as np
from pathlib import Path

# Try to import Piper
try:
    from piper.voice import PiperVoice
    PIPER_AVAILABLE = True
except ImportError:
    print("⚠️ Piper not available, using mock TTS")
    PIPER_AVAILABLE = False

# ==========================================
# CONFIGURATION - Use relative paths
# ==========================================
BASE_DIR = Path(__file__).resolve().parent
MODEL_PATH = BASE_DIR / "Voices" / "en_US-amy-medium.onnx"
CONFIG_PATH = BASE_DIR / "Voices" / "en_US-amy-medium.onnx.json"

print(f"📍 TTS Model path: {MODEL_PATH}")
print(f"📍 TTS Config path: {CONFIG_PATH}")
print(f"📍 Model exists: {MODEL_PATH.exists()}")
print(f"📍 Config exists: {CONFIG_PATH.exists()}")

_voice = None

# ==========================================
# MODEL LOADING
# ==========================================
def load_piper_model():
    """Load the Piper TTS model (lazy loading)"""
    global _voice
    
    if _voice:
        return _voice
        
    if not PIPER_AVAILABLE:
        print("⚠️ Piper library not available")
        return None
        
    if not MODEL_PATH.exists() or not CONFIG_PATH.exists():
        print("❌ Piper model/config files missing")
        print(f"   Expected model: {MODEL_PATH}")
        print(f"   Expected config: {CONFIG_PATH}")
        return None
        
    try:
        print("⏳ Loading Piper TTS model...")
        _voice = PiperVoice.load(str(MODEL_PATH), config_path=str(CONFIG_PATH))
        print("✅ Piper loaded successfully")
    except Exception as e:
        print(f"❌ Failed to load Piper model: {e}")
        _voice = None
        
    return _voice

# ==========================================
# AUDIO PLAYBACK
# ==========================================
def safe_play(audio_int16, sample_rate):
    """
    Try playing audio, fallback to printing if device unavailable.
    
    Args:
        audio_int16: Audio data as int16 numpy array
        sample_rate: Sample rate in Hz
    
    Returns:
        True if playback succeeded, False otherwise
    """
    try:
        sd.play(audio_int16, samplerate=sample_rate)
        sd.wait()
        return True
    except Exception as e:
        print(f"❌ Audio playback failed: {e}")
        return False

# ==========================================
# MAIN SPEAK FUNCTION
# ==========================================
def speak(text: str):
    """
    Synthesize and speak the given text.
    Falls back to text output if TTS unavailable.
    
    Args:
        text: Text to speak
    """
    voice = load_piper_model()
    
    # Fallback mode if Piper unavailable
    if not voice:
        print(f"🔊 [Text-Only Mode]: {text}")
        return

    try:
        # Generate audio
        chunks = list(voice.synthesize(text))
        
        if not chunks:
            print("❌ No audio generated by Piper")
            print(f"🔊 [Fallback]: {text}")
            return

        # Process audio
        audio_float = np.concatenate([chunk.audio_float_array for chunk in chunks])
        
        # Normalize
        max_val = np.max(np.abs(audio_float))
        if max_val > 0:
            audio_float = audio_float / max_val
        
        # Convert to int16
        audio_int16 = (audio_float * 32767).astype(np.int16)
        
        # Get sample rate
        sample_rate = chunks[0].sample_rate
        
        # Add silence padding (start + end)
        pad = np.zeros(int(0.3 * sample_rate), dtype=np.int16)
        audio_int16 = np.concatenate([pad, audio_int16, pad])

        # Speak
        print(f"🔊 Assistant speaking: '{text}'")
        
        if not safe_play(audio_int16, sample_rate):
            print(f"🔊 [Fallback]: {text}")

    except Exception as e:
        print(f"❌ Piper TTS Error: {e}")
        print(f"🔊 [Fallback]: {text}")

# ==========================================
# TEST
# ==========================================
if __name__ == "__main__":
    print("\n" + "="*50)
    print("PIPER TTS TEST")
    print("="*50)
    print(f"Piper available: {PIPER_AVAILABLE}")
    print(f"Model exists: {MODEL_PATH.exists()}")
    print("="*50 + "\n")
    
    test_phrases = [
        "Hello! This is a test of the assistant voice.",
        "The quick brown fox jumps over the lazy dog.",
        "How are you doing today?"
    ]
    
    for phrase in test_phrases:
        print(f"\nTesting: {phrase}")
        speak(phrase)
        print()