import sounddevice as sd
import numpy as np
from pathlib import Path

try:
    from piper.voice import PiperVoice
    PIPER_AVAILABLE = True
except ImportError:
    print("⚠️ Piper not available, using mock TTS")
    PIPER_AVAILABLE = False

BASE_DIR = Path(__file__).resolve().parent
MODEL_PATH = BASE_DIR / "Voices" / "en_US-amy-medium.onnx"
CONFIG_PATH = BASE_DIR / "Voices" / "en_US-amy-medium.onnx.json"

_voice = None

def load_piper_model():
    global _voice
    if _voice:
        return _voice
    if not PIPER_AVAILABLE:
        return None
    if not MODEL_PATH.exists() or not CONFIG_PATH.exists():
        print("❌ Piper model/config missing. Using fallback TTS.")
        return None
    try:
        _voice = PiperVoice.load(str(MODEL_PATH), config_path=str(CONFIG_PATH))
        print("✅ Piper loaded successfully")
    except Exception as e:
        print(f"❌ Failed to load Piper model: {e}")
        _voice = None
    return _voice

def safe_play(audio_int16, sample_rate):
    """Try playing audio, fallback to printing if device unavailable."""
    try:
        sd.play(audio_int16, samplerate=sample_rate)
        sd.wait()
    except Exception as e:
        print(f"❌ Audio playback failed: {e}")
        return False
    return True

def speak(text: str):
    voice = load_piper_model()
    if not voice:
        # fallback mode
        print(f"🔊 [Fallback TTS]: {text}")
        return

    try:
        chunks = list(voice.synthesize(text))
        if not chunks:
            print("❌ No audio generated by Piper")
            print(f"🔊 [Fallback TTS]: {text}")
            return

        audio_float = np.concatenate([chunk.audio_float_array for chunk in chunks])
        audio_float = audio_float / np.max(np.abs(audio_float))
        audio_int16 = (audio_float * 32767).astype(np.int16)
        sample_rate = chunks[0].sample_rate
        pad = np.zeros(int(0.3 * sample_rate), dtype=np.int16)
        audio_int16 = np.concatenate([pad, audio_int16, pad])

        print(f"Assistant speaking: '{text}'")
        if not safe_play(audio_int16, sample_rate):
            print(f"🔊 [Fallback TTS]: {text}")

    except Exception as e:
        print(f"❌ Piper TTS Error: {e}")
        print(f"🔊 [Fallback TTS]: {text}")

# ======================
# TEST
# ======================
if __name__ == "__main__":
    speak("Hello! This is a test of the assistant voice.")
